//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szakdoga.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szakdoga.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both height and width..
        /// </summary>
        internal static string AddHeightWidthPrompt {
            get {
                return ResourceManager.GetString("AddHeightWidthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all pieces?.
        /// </summary>
        internal static string ConfirmClearText {
            get {
                return ResourceManager.GetString("ConfirmClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height and width must be greater than zero..
        /// </summary>
        internal static string DimensionErrorText {
            get {
                return ResourceManager.GetString("DimensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing
        ///needed.
        /// </summary>
        internal static string EdgeSealingNeededLabel {
            get {
                return ResourceManager.GetString("EdgeSealingNeededLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pieces to optimize..
        /// </summary>
        internal static string EmptyListError {
            get {
                return ResourceManager.GetString("EmptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid count format. Please enter a valid number..
        /// </summary>
        internal static string InvalidNumberCount {
            get {
                return ResourceManager.GetString("InvalidNumberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid height format. Please enter a valid number..
        /// </summary>
        internal static string InvalidNumberHeight {
            get {
                return ResourceManager.GetString("InvalidNumberHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid width format. Please enter a valid number..
        /// </summary>
        internal static string InvalidNumberWidth {
            get {
                return ResourceManager.GetString("InvalidNumberWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during loading.
        /// </summary>
        internal static string LoadErrorText {
            get {
                return ResourceManager.GetString("LoadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load pieces list.
        /// </summary>
        internal static string LoadPromptText {
            get {
                return ResourceManager.GetString("LoadPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material
        ///utilization.
        /// </summary>
        internal static string MaterialUtilizationLabel {
            get {
                return ResourceManager.GetString("MaterialUtilizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material utilization
        ///this sheet.
        /// </summary>
        internal static string MaterialUtilThisSheetLabel {
            get {
                return ResourceManager.GetString("MaterialUtilThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string NextSheetButton {
            get {
                return ResourceManager.GetString("NextSheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of
        ///pieces.
        /// </summary>
        internal static string NoOfPiecesLabel {
            get {
                return ResourceManager.GetString("NoOfPiecesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of
        ///sheets.
        /// </summary>
        internal static string NoOfSheetsLabel {
            get {
                return ResourceManager.GetString("NoOfSheetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimise.
        /// </summary>
        internal static string OptimiseButton {
            get {
                return ResourceManager.GetString("OptimiseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces this
        ///sheet.
        /// </summary>
        internal static string PiecesThisSheetLabel {
            get {
                return ResourceManager.GetString("PiecesThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string PrevSheetButton {
            get {
                return ResourceManager.GetString("PrevSheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross direction.
        /// </summary>
        internal static string RadioCrossDir {
            get {
                return ResourceManager.GetString("RadioCrossDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain direction.
        /// </summary>
        internal static string RadioGrainDir {
            get {
                return ResourceManager.GetString("RadioGrainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guillotine.
        /// </summary>
        internal static string RadioGuillotineOpt {
            get {
                return ResourceManager.GetString("RadioGuillotineOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heusristic.
        /// </summary>
        internal static string RadioHeuristicOpt {
            get {
                return ResourceManager.GetString("RadioHeuristicOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string RadioTestOpt {
            get {
                return ResourceManager.GetString("RadioTestOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable direction.
        /// </summary>
        internal static string RadioVariableDir {
            get {
                return ResourceManager.GetString("RadioVariableDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A piece with the same dimensions and cut direction already exists. Continue?.
        /// </summary>
        internal static string SamePiecePromt {
            get {
                return ResourceManager.GetString("SamePiecePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving pieces.
        /// </summary>
        internal static string SaveErrorText {
            get {
                return ResourceManager.GetString("SaveErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save pieces list.
        /// </summary>
        internal static string SavePromptText {
            get {
                return ResourceManager.GetString("SavePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces saved successfully..
        /// </summary>
        internal static string SaveSuccessText {
            get {
                return ResourceManager.GetString("SaveSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade thickness.
        /// </summary>
        internal static string SettingsBladeThicknessLabel {
            get {
                return ResourceManager.GetString("SettingsBladeThicknessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing cost.
        /// </summary>
        internal static string SettingsEdgeSealingCostLabel {
            get {
                return ResourceManager.GetString("SettingsEdgeSealingCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string SettingsHeightLabel {
            get {
                return ResourceManager.GetString("SettingsHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet color.
        /// </summary>
        internal static string SettingsSheetColor {
            get {
                return ResourceManager.GetString("SettingsSheetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet cost.
        /// </summary>
        internal static string SettingsSheetCostLabel {
            get {
                return ResourceManager.GetString("SettingsSheetCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet manufacturer.
        /// </summary>
        internal static string SettingsSheetManufacturerLabel {
            get {
                return ResourceManager.GetString("SettingsSheetManufacturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet padding.
        /// </summary>
        internal static string SettingsSheetPaddingLabel {
            get {
                return ResourceManager.GetString("SettingsSheetPaddingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string SettingsWidthLabel {
            get {
                return ResourceManager.GetString("SettingsWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutOptimizer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total area of
        ///pieces.
        /// </summary>
        internal static string TotalAreaOfPiecesLabel {
            get {
                return ResourceManager.GetString("TotalAreaOfPiecesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        internal static string TotalCostLabel {
            get {
                return ResourceManager.GetString("TotalCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cut
        ///length.
        /// </summary>
        internal static string TotalCutLengthLabel {
            get {
                return ResourceManager.GetString("TotalCutLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing
        ///cost.
        /// </summary>
        internal static string TotalEdgeSealingCostLabel {
            get {
                return ResourceManager.GetString("TotalEdgeSealingCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sheet
        ///cost.
        /// </summary>
        internal static string TotalSheetCostLabel {
            get {
                return ResourceManager.GetString("TotalSheetCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total waste
        ///area.
        /// </summary>
        internal static string TotalWasteAreaLabel {
            get {
                return ResourceManager.GetString("TotalWasteAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste area
        ///this sheet.
        /// </summary>
        internal static string WasteAreaThisSheetLabel {
            get {
                return ResourceManager.GetString("WasteAreaThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
    }
}
