//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szakdoga.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szakdoga.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing
        ///needed.
        /// </summary>
        public static string EdgeSealingNeededLabel {
            get {
                return ResourceManager.GetString("EdgeSealingNeededLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material
        ///utilization.
        /// </summary>
        public static string MaterialUtilizationLabel {
            get {
                return ResourceManager.GetString("MaterialUtilizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material utilization
        ///this sheet.
        /// </summary>
        public static string MaterialUtilThisSheetLabel {
            get {
                return ResourceManager.GetString("MaterialUtilThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string NextSheetButton {
            get {
                return ResourceManager.GetString("NextSheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of
        ///pieces.
        /// </summary>
        public static string NoOfPiecesLabel {
            get {
                return ResourceManager.GetString("NoOfPiecesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of
        ///sheets.
        /// </summary>
        public static string NoOfSheetsLabel {
            get {
                return ResourceManager.GetString("NoOfSheetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimise.
        /// </summary>
        public static string OptimiseButton {
            get {
                return ResourceManager.GetString("OptimiseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces this
        ///sheet.
        /// </summary>
        public static string PiecesThisSheetLabel {
            get {
                return ResourceManager.GetString("PiecesThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string PrevSheetButton {
            get {
                return ResourceManager.GetString("PrevSheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross direction.
        /// </summary>
        public static string RadioCrossDir {
            get {
                return ResourceManager.GetString("RadioCrossDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain direction.
        /// </summary>
        public static string RadioGrainDir {
            get {
                return ResourceManager.GetString("RadioGrainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guillotine.
        /// </summary>
        public static string RadioGuillotineOpt {
            get {
                return ResourceManager.GetString("RadioGuillotineOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heusristic.
        /// </summary>
        public static string RadioHeuristicOpt {
            get {
                return ResourceManager.GetString("RadioHeuristicOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string RadioTestOpt {
            get {
                return ResourceManager.GetString("RadioTestOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable direction.
        /// </summary>
        public static string RadioVariableDir {
            get {
                return ResourceManager.GetString("RadioVariableDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade thickness.
        /// </summary>
        public static string SettingsBladeThicknessLabel {
            get {
                return ResourceManager.GetString("SettingsBladeThicknessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing cost.
        /// </summary>
        public static string SettingsEdgeSealingCostLabel {
            get {
                return ResourceManager.GetString("SettingsEdgeSealingCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string SettingsHeightLabel {
            get {
                return ResourceManager.GetString("SettingsHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet color.
        /// </summary>
        public static string SettingsSheetColor {
            get {
                return ResourceManager.GetString("SettingsSheetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet cost.
        /// </summary>
        public static string SettingsSheetCostLabel {
            get {
                return ResourceManager.GetString("SettingsSheetCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet manufacturer.
        /// </summary>
        public static string SettingsSheetManufacturerLabel {
            get {
                return ResourceManager.GetString("SettingsSheetManufacturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet padding.
        /// </summary>
        public static string SettingsSheetPaddingLabel {
            get {
                return ResourceManager.GetString("SettingsSheetPaddingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string SettingsWidthLabel {
            get {
                return ResourceManager.GetString("SettingsWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutOptimizer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total area of
        ///pieces.
        /// </summary>
        public static string TotalAreaOfPiecesLabel {
            get {
                return ResourceManager.GetString("TotalAreaOfPiecesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        public static string TotalCostLabel {
            get {
                return ResourceManager.GetString("TotalCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cut
        ///length.
        /// </summary>
        public static string TotalCutLengthLabel {
            get {
                return ResourceManager.GetString("TotalCutLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing
        ///cost.
        /// </summary>
        public static string TotalEdgeSealingCostLabel {
            get {
                return ResourceManager.GetString("TotalEdgeSealingCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sheet
        ///cost.
        /// </summary>
        public static string TotalSheetCostLabel {
            get {
                return ResourceManager.GetString("TotalSheetCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total waste
        ///area.
        /// </summary>
        public static string TotalWasteAreaLabel {
            get {
                return ResourceManager.GetString("TotalWasteAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste area
        ///this sheet.
        /// </summary>
        public static string WasteAreaThisSheetLabel {
            get {
                return ResourceManager.GetString("WasteAreaThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
    }
}
