//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szakdoga.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szakdoga.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both height and width..
        /// </summary>
        internal static string AddHeightWidthPrompt {
            get {
                return ResourceManager.GetString("AddHeightWidthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new
        ///customer.
        /// </summary>
        internal static string AddNewCustomerLabel {
            get {
                return ResourceManager.GetString("AddNewCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New
        ///Order.
        /// </summary>
        internal static string AddNewOrderLabel {
            get {
                return ResourceManager.GetString("AddNewOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new order.
        /// </summary>
        internal static string AddNewOrderTitle {
            get {
                return ResourceManager.GetString("AddNewOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new
        ///sheet.
        /// </summary>
        internal static string AddNewSheetLabel {
            get {
                return ResourceManager.GetString("AddNewSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete customer.
        /// </summary>
        internal static string CDTitle {
            get {
                return ResourceManager.GetString("CDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email....
        /// </summary>
        internal static string CIEmailHint {
            get {
                return ResourceManager.GetString("CIEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string CIEmailLabel {
            get {
                return ResourceManager.GetString("CIEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name....
        /// </summary>
        internal static string CINameHint {
            get {
                return ResourceManager.GetString("CINameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You MUST input a name!.
        /// </summary>
        internal static string CINameIsEmpty {
            get {
                return ResourceManager.GetString("CINameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string CINameLabel {
            get {
                return ResourceManager.GetString("CINameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +36301234567.
        /// </summary>
        internal static string CIPhoneHint {
            get {
                return ResourceManager.GetString("CIPhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number:.
        /// </summary>
        internal static string CIPhoneLabel {
            get {
                return ResourceManager.GetString("CIPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new customer.
        /// </summary>
        internal static string CITitle {
            get {
                return ResourceManager.GetString("CITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        internal static string CMCustomerLabel {
            get {
                return ResourceManager.GetString("CMCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify customer.
        /// </summary>
        internal static string CMTitle {
            get {
                return ResourceManager.GetString("CMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all pieces?.
        /// </summary>
        internal static string ConfirmClearText {
            get {
                return ResourceManager.GetString("ConfirmClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string ConfrimDelete {
            get {
                return ResourceManager.GetString("ConfrimDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without order.
        /// </summary>
        internal static string ContinueWithoutOrder {
            get {
                return ResourceManager.GetString("ContinueWithoutOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut diagram.
        /// </summary>
        internal static string CutDiagramTitle {
            get {
                return ResourceManager.GetString("CutDiagramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///customer.
        /// </summary>
        internal static string DeleteCustomerLabel {
            get {
                return ResourceManager.GetString("DeleteCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///order.
        /// </summary>
        internal static string DeleteOrderLabel {
            get {
                return ResourceManager.GetString("DeleteOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///sheet.
        /// </summary>
        internal static string DeleteSheetLabel {
            get {
                return ResourceManager.GetString("DeleteSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height and width must be greater than zero..
        /// </summary>
        internal static string DimensionErrorText {
            get {
                return ResourceManager.GetString("DimensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing
        ///needed.
        /// </summary>
        internal static string EdgeSealingNeededLabel {
            get {
                return ResourceManager.GetString("EdgeSealingNeededLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pieces to optimize..
        /// </summary>
        internal static string EmptyListError {
            get {
                return ResourceManager.GetString("EmptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order.
        /// </summary>
        internal static string EmptyOrderTitle {
            get {
                return ResourceManager.GetString("EmptyOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To export optimize first..
        /// </summary>
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to inventory.
        /// </summary>
        internal static string IEAddInventoryButton {
            get {
                return ResourceManager.GetString("IEAddInventoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid count format. Please enter a valid number..
        /// </summary>
        internal static string InvalidNumberCount {
            get {
                return ResourceManager.GetString("InvalidNumberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid height format. Please enter a valid number..
        /// </summary>
        internal static string InvalidNumberHeight {
            get {
                return ResourceManager.GetString("InvalidNumberHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid width format. Please enter a valid number..
        /// </summary>
        internal static string InvalidNumberWidth {
            get {
                return ResourceManager.GetString("InvalidNumberWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during loading.
        /// </summary>
        internal static string LoadErrorText {
            get {
                return ResourceManager.GetString("LoadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load pieces list.
        /// </summary>
        internal static string LoadPromptText {
            get {
                return ResourceManager.GetString("LoadPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage inventory.
        /// </summary>
        internal static string ManageInventoryButton {
            get {
                return ResourceManager.GetString("ManageInventoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material
        ///utilization.
        /// </summary>
        internal static string MaterialUtilizationLabel {
            get {
                return ResourceManager.GetString("MaterialUtilizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material utilization
        ///this sheet.
        /// </summary>
        internal static string MaterialUtilThisSheetLabel {
            get {
                return ResourceManager.GetString("MaterialUtilThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify
        ///Customer.
        /// </summary>
        internal static string ModifyCustomerLabel {
            get {
                return ResourceManager.GetString("ModifyCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify
        ///order.
        /// </summary>
        internal static string ModifyOderLabel {
            get {
                return ResourceManager.GetString("ModifyOderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify
        ///sheet.
        /// </summary>
        internal static string ModifySheetLabel {
            get {
                return ResourceManager.GetString("ModifySheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string NextSheetButton {
            get {
                return ResourceManager.GetString("NextSheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer to delete it.
        /// </summary>
        internal static string NoCustomerSelectedForDelete {
            get {
                return ResourceManager.GetString("NoCustomerSelectedForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer to modify it.
        /// </summary>
        internal static string NoCustomerSelectedForModify {
            get {
                return ResourceManager.GetString("NoCustomerSelectedForModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of
        ///pieces.
        /// </summary>
        internal static string NoOfPiecesLabel {
            get {
                return ResourceManager.GetString("NoOfPiecesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of
        ///sheets.
        /// </summary>
        internal static string NoOfSheetsLabel {
            get {
                return ResourceManager.GetString("NoOfSheetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an order to delete.
        /// </summary>
        internal static string NoOrderSelectedForDelete {
            get {
                return ResourceManager.GetString("NoOrderSelectedForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelase select an order to update.
        /// </summary>
        internal static string NoOrderSelectedForModify {
            get {
                return ResourceManager.GetString("NoOrderSelectedForModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name:.
        /// </summary>
        internal static string OICustomerNameLabel {
            get {
                return ResourceManager.GetString("OICustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order title.
        /// </summary>
        internal static string OIOrderTitleHint {
            get {
                return ResourceManager.GetString("OIOrderTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order title.
        /// </summary>
        internal static string OIOrderTitleLabel {
            get {
                return ResourceManager.GetString("OIOrderTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet name:.
        /// </summary>
        internal static string OISheetNameLabel {
            get {
                return ResourceManager.GetString("OISheetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an order to view details..
        /// </summary>
        internal static string OpenOrderError {
            get {
                return ResourceManager.GetString("OpenOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize.
        /// </summary>
        internal static string OptimiseButton {
            get {
                return ResourceManager.GetString("OptimiseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces this
        ///sheet.
        /// </summary>
        internal static string PiecesThisSheetLabel {
            get {
                return ResourceManager.GetString("PiecesThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string PrevSheetButton {
            get {
                return ResourceManager.GetString("PrevSheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project explorer.
        /// </summary>
        internal static string ProjectExplorerButton {
            get {
                return ResourceManager.GetString("ProjectExplorerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross direction.
        /// </summary>
        internal static string RadioCrossDir {
            get {
                return ResourceManager.GetString("RadioCrossDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain direction.
        /// </summary>
        internal static string RadioGrainDir {
            get {
                return ResourceManager.GetString("RadioGrainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guillotine.
        /// </summary>
        internal static string RadioGuillotineOpt {
            get {
                return ResourceManager.GetString("RadioGuillotineOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heusristic.
        /// </summary>
        internal static string RadioHeuristicOpt {
            get {
                return ResourceManager.GetString("RadioHeuristicOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick.
        /// </summary>
        internal static string RadioTestOpt {
            get {
                return ResourceManager.GetString("RadioTestOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable direction.
        /// </summary>
        internal static string RadioVariableDir {
            get {
                return ResourceManager.GetString("RadioVariableDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A piece with the same dimensions and cut direction already exists. Continue?.
        /// </summary>
        internal static string SamePiecePromt {
            get {
                return ResourceManager.GetString("SamePiecePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving pieces.
        /// </summary>
        internal static string SaveErrorText {
            get {
                return ResourceManager.GetString("SaveErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save pieces list.
        /// </summary>
        internal static string SavePromptText {
            get {
                return ResourceManager.GetString("SavePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces saved successfully..
        /// </summary>
        internal static string SaveSuccessText {
            get {
                return ResourceManager.GetString("SaveSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save pieces list to a separate file?.
        /// </summary>
        internal static string SaveToTxtOrOnlyDb {
            get {
                return ResourceManager.GetString("SaveToTxtOrOnlyDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a sheet to delete it.
        /// </summary>
        internal static string SDNoSheetSelectedForDelete {
            get {
                return ResourceManager.GetString("SDNoSheetSelectedForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sheet.
        /// </summary>
        internal static string SDTitle {
            get {
                return ResourceManager.GetString("SDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade thickness.
        /// </summary>
        internal static string SettingsBladeThicknessLabel {
            get {
                return ResourceManager.GetString("SettingsBladeThicknessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing cost.
        /// </summary>
        internal static string SettingsEdgeSealingCostLabel {
            get {
                return ResourceManager.GetString("SettingsEdgeSealingCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string SettingsHeightLabel {
            get {
                return ResourceManager.GetString("SettingsHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet color.
        /// </summary>
        internal static string SettingsSheetColor {
            get {
                return ResourceManager.GetString("SettingsSheetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet cost.
        /// </summary>
        internal static string SettingsSheetCostLabel {
            get {
                return ResourceManager.GetString("SettingsSheetCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet manufacturer.
        /// </summary>
        internal static string SettingsSheetManufacturerLabel {
            get {
                return ResourceManager.GetString("SettingsSheetManufacturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet padding.
        /// </summary>
        internal static string SettingsSheetPaddingLabel {
            get {
                return ResourceManager.GetString("SettingsSheetPaddingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for width, height, price, and color only apply when the order has no sheet selected..
        /// </summary>
        internal static string SettingsTooltipText {
            get {
                return ResourceManager.GetString("SettingsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string SettingsWidthLabel {
            get {
                return ResourceManager.GetString("SettingsWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet padding is too large for the sheet.
        /// </summary>
        internal static string SheetPaddingTooLarge {
            get {
                return ResourceManager.GetString("SheetPaddingTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color....
        /// </summary>
        internal static string SIColorHint {
            get {
                return ResourceManager.GetString("SIColorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string SIColorLabel {
            get {
                return ResourceManager.GetString("SIColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description....
        /// </summary>
        internal static string SIDescriptionHint {
            get {
                return ResourceManager.GetString("SIDescriptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string SIDescriptionLabel {
            get {
                return ResourceManager.GetString("SIDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters can not be negative!.
        /// </summary>
        internal static string SIDimensionError {
            get {
                return ResourceManager.GetString("SIDimensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height... (1234.0).
        /// </summary>
        internal static string SIHeightHint {
            get {
                return ResourceManager.GetString("SIHeightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You MUST input a height!.
        /// </summary>
        internal static string SIHeightIsEmpty {
            get {
                return ResourceManager.GetString("SIHeightIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        internal static string SIHeightLabel {
            get {
                return ResourceManager.GetString("SIHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name....
        /// </summary>
        internal static string SINameHint {
            get {
                return ResourceManager.GetString("SINameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You MUST input a name!.
        /// </summary>
        internal static string SINameIsEmpty {
            get {
                return ResourceManager.GetString("SINameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string SINameLabel {
            get {
                return ResourceManager.GetString("SINameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pice... (1234.0).
        /// </summary>
        internal static string SIPriceHint {
            get {
                return ResourceManager.GetString("SIPriceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string SIPriceLabel {
            get {
                return ResourceManager.GetString("SIPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sheet.
        /// </summary>
        internal static string SITitle {
            get {
                return ResourceManager.GetString("SITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width... (1234.0).
        /// </summary>
        internal static string SIWidthHint {
            get {
                return ResourceManager.GetString("SIWidthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You MUST input a width!.
        /// </summary>
        internal static string SIWidthIsEmpty {
            get {
                return ResourceManager.GetString("SIWidthIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        internal static string SIWidthLabel {
            get {
                return ResourceManager.GetString("SIWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a sheet to modify it.
        /// </summary>
        internal static string SMNoSheetSelectedForModify {
            get {
                return ResourceManager.GetString("SMNoSheetSelectedForModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        internal static string SMSSheetLabel {
            get {
                return ResourceManager.GetString("SMSSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify sheet.
        /// </summary>
        internal static string SMTitle {
            get {
                return ResourceManager.GetString("SMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutOptimizer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total area of
        ///pieces.
        /// </summary>
        internal static string TotalAreaOfPiecesLabel {
            get {
                return ResourceManager.GetString("TotalAreaOfPiecesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        internal static string TotalCostLabel {
            get {
                return ResourceManager.GetString("TotalCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cut
        ///length.
        /// </summary>
        internal static string TotalCutLengthLabel {
            get {
                return ResourceManager.GetString("TotalCutLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge sealing
        ///cost.
        /// </summary>
        internal static string TotalEdgeSealingCostLabel {
            get {
                return ResourceManager.GetString("TotalEdgeSealingCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sheet
        ///cost.
        /// </summary>
        internal static string TotalSheetCostLabel {
            get {
                return ResourceManager.GetString("TotalSheetCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total waste
        ///area.
        /// </summary>
        internal static string TotalWasteAreaLabel {
            get {
                return ResourceManager.GetString("TotalWasteAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownPieceName {
            get {
                return ResourceManager.GetString("UnknownPieceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update order.
        /// </summary>
        internal static string UpdateOrderTitle {
            get {
                return ResourceManager.GetString("UpdateOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste area
        ///this sheet.
        /// </summary>
        internal static string WasteAreaThisSheetLabel {
            get {
                return ResourceManager.GetString("WasteAreaThisSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet sizes must be positive.
        /// </summary>
        internal static string WrongSheetSizes {
            get {
                return ResourceManager.GetString("WrongSheetSizes", resourceCulture);
            }
        }
    }
}
